### PR TITLE
Update to 1.3.0

### PR DESCRIPTION
**Pull request by jschueller**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by djsutherland** [comment]
@conda-forge-admin, please rererender

`python >=3.5` requirements only works for `noarch` packages; need to use plain `python` and add `skip`s for "arched" packages.

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by djsutherland** [comment]
The bot doesn't know how to handle errors in rerendering properly; we need to fix that... But the problem was that I never remember how these version variables work:
 
```
Error: Invalid selector in meta.yaml line 15:
offending line:
  skip: true  # [python < 3.5]
exception:
'<' not supported between instances of 'str' and 'float'
```

**Pull request merged**
